config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/', as: 'rails_admin'
  resources :detail_classes
  resources :header_classes
  resources :shcedules
  resources :shcedules
  resources :checks
  resources :subscriptions
  resources :memberships
  resources :product_quantities
  resources :products
  resources :providers
  resources :sales
  resources :services
  resources :users
  resources :products
  resources :clients

end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :sale
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :subscriptions
	has_many :sales
	has_many :detail_classes
end

app/models/detail_class.rb
class DetailClass < ActiveRecord::Base
  belongs_to :client
  belongs_to :header_class
  belongs_to :subscription
end

app/models/header_class.rb
class HeaderClass < ActiveRecord::Base
  belongs_to :service
  belongs_to :shcedule
  has_many :detail_classes, dependent: :destroy
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :service
  has_many :subscriptions
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :provider
  has_many :product_quantities

  def type_enum
		['Bebidas','Comestibles','Proteinas','Accesorios']
	end
end

app/models/product_quantity.rb
class ProductQuantity < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :products
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  has_many :subscription, dependent: :destroy
  has_many :product_quantities , dependent: :destroy
  has_many :checks, dependent: :destroy
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :memberships
	has_many :subscriptions
	has_many :header_classes
end

app/models/shcedule.rb
class Shcedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :client
  belongs_to :service
  belongs_to :membership
  belongs_to :sale
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    has_many :shcedules
	has_many :sales

	def position_enum
		['Admin','Cajero','Profesor','Conserje']
	end
end

app/controllers/header_classes_controller.rb
class HeaderClassesController < ApplicationController
  before_action :set_header_class, only: [:show, :edit, :update, :destroy]

  # GET /header_classes
  # GET /header_classes.json
  def index
    @header_classes = HeaderClass.all
  end

  # GET /header_classes/1
  # GET /header_classes/1.json
  def show
  end

  # GET /header_classes/new
  def new
    @header_class = HeaderClass.new
  end

  # GET /header_classes/1/edit
  def edit
  end

  # POST /header_classes
  # POST /header_classes.json
  def create
    @header_class = HeaderClass.new(header_class_params)

    respond_to do |format|
      if @header_class.save
        format.html { redirect_to @header_class, notice: 'Header class was successfully created.' }
        format.json { render :show, status: :created, location: @header_class }
      else
        format.html { render :new }
        format.json { render json: @header_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /header_classes/1
  # PATCH/PUT /header_classes/1.json
  def update
    respond_to do |format|
      if @header_class.update(header_class_params)
        format.html { redirect_to @header_class, notice: 'Header class was successfully updated.' }
        format.json { render :show, status: :ok, location: @header_class }
      else
        format.html { render :edit }
        format.json { render json: @header_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /header_classes/1
  # DELETE /header_classes/1.json
  def destroy
    @header_class.destroy
    respond_to do |format|
      format.html { redirect_to header_classes_url, notice: 'Header class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_header_class
      @header_class = HeaderClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def header_class_params
      params.require(:header_class).permit(:date, :start_time, :end_time, :maximum_capacity, :registered, :service_id, :shcedule_id, :teacher)
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/header_classes_helper.rb
module HeaderClassesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/header_classes/_form.html.erb
<%= form_for(@header_class) do |f| %>
  <% if @header_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@header_class.errors.count, "error") %> prohibited this header_class from being saved:</h2>

      <ul>
      <% @header_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :maximum_capacity %><br>
    <%= f.number_field :maximum_capacity %>
  </div>
  <div class="field">
    <%= f.label :registered %><br>
    <%= f.number_field :registered %>
  </div>
  <div class="field">
    <%= f.label :service_id %><br>
    <%= f.text_field :service_id %>
  </div>
  <div class="field">
    <%= f.label :shcedule_id %><br>
    <%= f.text_field :shcedule_id %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/header_classes/edit.html.erb
<h1>Editing Header Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @header_class %> |
<%= link_to 'Back', header_classes_path %>

app/views/header_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Header Classes</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Maximum capacity</th>
      <th>Registered</th>
      <th>Service</th>
      <th>Shcedule</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @header_classes.each do |header_class| %>
      <tr>
        <td><%= header_class.date %></td>
        <td><%= header_class.start_time %></td>
        <td><%= header_class.end_time %></td>
        <td><%= header_class.maximum_capacity %></td>
        <td><%= header_class.registered %></td>
        <td><%= header_class.service %></td>
        <td><%= header_class.shcedule %></td>
        <td><%= header_class.teacher %></td>
        <td><%= link_to 'Show', header_class %></td>
        <td><%= link_to 'Edit', edit_header_class_path(header_class) %></td>
        <td><%= link_to 'Destroy', header_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Header class', new_header_class_path %>

app/views/header_classes/new.html.erb
<h1>New Header Class</h1>

<%= render 'form' %>

<%= link_to 'Back', header_classes_path %>

app/views/header_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @header_class.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @header_class.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @header_class.end_time %>
</p>

<p>
  <strong>Maximum capacity:</strong>
  <%= @header_class.maximum_capacity %>
</p>

<p>
  <strong>Registered:</strong>
  <%= @header_class.registered %>
</p>

<p>
  <strong>Service:</strong>
  <%= @header_class.service %>
</p>

<p>
  <strong>Shcedule:</strong>
  <%= @header_class.shcedule %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @header_class.teacher %>
</p>

<%= link_to 'Edit', edit_header_class_path(@header_class) %> |
<%= link_to 'Back', header_classes_path %>