config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/', as: 'rails_admin'
  resources :detail_classes
  resources :header_classes
  resources :shcedules
  resources :shcedules
  resources :checks
  resources :subscriptions
  resources :memberships
  resources :product_quantities
  resources :products
  resources :providers
  resources :sales
  resources :services
  resources :users
  resources :products
  resources :clients

end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :sale
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :subscriptions
	has_many :sales
	has_many :detail_classes
end

app/models/detail_class.rb
class DetailClass < ActiveRecord::Base
  belongs_to :client
  belongs_to :header_class
  belongs_to :subscription
end

app/models/header_class.rb
class HeaderClass < ActiveRecord::Base
  belongs_to :service
  belongs_to :shcedule
  has_many :detail_classes, dependent: :destroy
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :service
  has_many :subscriptions
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :provider
  has_many :product_quantities

  def type_enum
		['Bebidas','Comestibles','Proteinas','Accesorios']
	end
end

app/models/product_quantity.rb
class ProductQuantity < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :products
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  has_many :subscription, dependent: :destroy
  has_many :product_quantities , dependent: :destroy
  has_many :checks, dependent: :destroy
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :memberships
	has_many :subscriptions
	has_many :header_classes
end

app/models/shcedule.rb
class Shcedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :client
  belongs_to :service
  belongs_to :membership
  belongs_to :sale
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    has_many :shcedules
	has_many :sales

	def position_enum
		['Admin','Cajero','Profesor','Conserje']
	end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:client_id, :start_time, :end_time, :service_id, :membership_id, :total_entries, :current_entries, :state, :sale_id)
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shcedules_helper.rb
module ShcedulesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.date_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.date_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :service_id %><br>
    <%= f.text_field :service_id %>
  </div>
  <div class="field">
    <%= f.label :membership_id %><br>
    <%= f.text_field :membership_id %>
  </div>
  <div class="field">
    <%= f.label :total_entries %><br>
    <%= f.number_field :total_entries %>
  </div>
  <div class="field">
    <%= f.label :current_entries %><br>
    <%= f.number_field :current_entries %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :sale_id %><br>
    <%= f.text_field :sale_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Service</th>
      <th>Membership</th>
      <th>Total entries</th>
      <th>Current entries</th>
      <th>State</th>
      <th>Sale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.client %></td>
        <td><%= subscription.start_time %></td>
        <td><%= subscription.end_time %></td>
        <td><%= subscription.service %></td>
        <td><%= subscription.membership %></td>
        <td><%= subscription.total_entries %></td>
        <td><%= subscription.current_entries %></td>
        <td><%= subscription.state %></td>
        <td><%= subscription.sale %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @subscription.client %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @subscription.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @subscription.end_time %>
</p>

<p>
  <strong>Service:</strong>
  <%= @subscription.service %>
</p>

<p>
  <strong>Membership:</strong>
  <%= @subscription.membership %>
</p>

<p>
  <strong>Total entries:</strong>
  <%= @subscription.total_entries %>
</p>

<p>
  <strong>Current entries:</strong>
  <%= @subscription.current_entries %>
</p>

<p>
  <strong>State:</strong>
  <%= @subscription.state %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @subscription.sale %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>