config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/', as: 'rails_admin'
  resources :detail_classes
  resources :header_classes
  resources :shcedules
  resources :shcedules
  resources :checks
  resources :subscriptions
  resources :memberships
  resources :product_quantities
  resources :products
  resources :providers
  resources :sales
  resources :services
  resources :users
  resources :products
  resources :clients

end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :sale
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :subscriptions
	has_many :sales
	has_many :detail_classes
end

app/models/detail_class.rb
class DetailClass < ActiveRecord::Base
  belongs_to :client
  belongs_to :header_class
  belongs_to :subscription
end

app/models/header_class.rb
class HeaderClass < ActiveRecord::Base
  belongs_to :service
  belongs_to :shcedule
  has_many :detail_classes, dependent: :destroy
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :service
  has_many :subscriptions
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :provider
  has_many :product_quantities

  def type_enum
		['Bebidas','Comestibles','Proteinas','Accesorios']
	end
end

app/models/product_quantity.rb
class ProductQuantity < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :products
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  has_many :subscription, dependent: :destroy
  has_many :product_quantities , dependent: :destroy
  has_many :checks, dependent: :destroy
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :memberships
	has_many :subscriptions
	has_many :header_classes
end

app/models/shcedule.rb
class Shcedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :client
  belongs_to :service
  belongs_to :membership
  belongs_to :sale
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    has_many :shcedules
	has_many :sales

	def position_enum
		['Admin','Cajero','Profesor','Conserje']
	end
end

app/controllers/product_quantities_controller.rb
class ProductQuantitiesController < ApplicationController
  before_action :set_product_quantity, only: [:show, :edit, :update, :destroy]

  # GET /product_quantities
  # GET /product_quantities.json
  def index
    @product_quantities = ProductQuantity.all
  end

  # GET /product_quantities/1
  # GET /product_quantities/1.json
  def show
  end

  # GET /product_quantities/new
  def new
    @product_quantity = ProductQuantity.new
  end

  # GET /product_quantities/1/edit
  def edit
  end

  # POST /product_quantities
  # POST /product_quantities.json
  def create
    @product_quantity = ProductQuantity.new(product_quantity_params)

    respond_to do |format|
      if @product_quantity.save
        format.html { redirect_to @product_quantity, notice: 'Product quantity was successfully created.' }
        format.json { render :show, status: :created, location: @product_quantity }
      else
        format.html { render :new }
        format.json { render json: @product_quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_quantities/1
  # PATCH/PUT /product_quantities/1.json
  def update
    respond_to do |format|
      if @product_quantity.update(product_quantity_params)
        format.html { redirect_to @product_quantity, notice: 'Product quantity was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_quantity }
      else
        format.html { render :edit }
        format.json { render json: @product_quantity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_quantities/1
  # DELETE /product_quantities/1.json
  def destroy
    @product_quantity.destroy
    respond_to do |format|
      format.html { redirect_to product_quantities_url, notice: 'Product quantity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_quantity
      @product_quantity = ProductQuantity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_quantity_params
      params.require(:product_quantity).permit(:product_id, :quantity, :subtotal, :sale_id)
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/product_quantities_helper.rb
module ProductQuantitiesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shcedules_helper.rb
module ShcedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_quantities/_form.html.erb
<%= form_for(@product_quantity) do |f| %>
  <% if @product_quantity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_quantity.errors.count, "error") %> prohibited this product_quantity from being saved:</h2>

      <ul>
      <% @product_quantity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :subtotal %><br>
    <%= f.text_field :subtotal %>
  </div>
  <div class="field">
    <%= f.label :sale_id %><br>
    <%= f.text_field :sale_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_quantities/edit.html.erb
<h1>Editing Product Quantity</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_quantity %> |
<%= link_to 'Back', product_quantities_path %>

app/views/product_quantities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Quantities</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Subtotal</th>
      <th>Sale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_quantities.each do |product_quantity| %>
      <tr>
        <td><%= product_quantity.product %></td>
        <td><%= product_quantity.quantity %></td>
        <td><%= product_quantity.subtotal %></td>
        <td><%= product_quantity.sale %></td>
        <td><%= link_to 'Show', product_quantity %></td>
        <td><%= link_to 'Edit', edit_product_quantity_path(product_quantity) %></td>
        <td><%= link_to 'Destroy', product_quantity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product quantity', new_product_quantity_path %>

app/views/product_quantities/new.html.erb
<h1>New Product Quantity</h1>

<%= render 'form' %>

<%= link_to 'Back', product_quantities_path %>

app/views/product_quantities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_quantity.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product_quantity.quantity %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @product_quantity.subtotal %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @product_quantity.sale %>
</p>

<%= link_to 'Edit', edit_product_quantity_path(@product_quantity) %> |
<%= link_to 'Back', product_quantities_path %>