config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/', as: 'rails_admin'
  resources :detail_classes
  resources :header_classes
  resources :shcedules
  resources :shcedules
  resources :checks
  resources :subscriptions
  resources :memberships
  resources :product_quantities
  resources :products
  resources :providers
  resources :sales
  resources :services
  resources :users
  resources :products
  resources :clients

end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :sale
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :subscriptions
	has_many :sales
	has_many :detail_classes
end

app/models/detail_class.rb
class DetailClass < ActiveRecord::Base
  belongs_to :client
  belongs_to :header_class
  belongs_to :subscription
end

app/models/header_class.rb
class HeaderClass < ActiveRecord::Base
  belongs_to :service
  belongs_to :shcedule
  has_many :detail_classes, dependent: :destroy
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :service
  has_many :subscriptions
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :provider
  has_many :product_quantities

  def type_enum
		['Bebidas','Comestibles','Proteinas','Accesorios']
	end
end

app/models/product_quantity.rb
class ProductQuantity < ActiveRecord::Base
  belongs_to :product
  belongs_to :sale
end

app/models/provider.rb
class Provider < ActiveRecord::Base
	has_many :products
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  has_many :subscription, dependent: :destroy
  has_many :product_quantities , dependent: :destroy
  has_many :checks, dependent: :destroy
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :memberships
	has_many :subscriptions
	has_many :header_classes
end

app/models/shcedule.rb
class Shcedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :client
  belongs_to :service
  belongs_to :membership
  belongs_to :sale
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  extend Devise::Models
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    has_many :shcedules
	has_many :sales

	def position_enum
		['Admin','Cajero','Profesor','Conserje']
	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:date, :hour, :client_id, :user_id, :subtotal, :iva, :total_effective, :total_card, :total_checks, :nota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shcedules_helper.rb
module ShcedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :hour %><br>
    <%= f.text_field :hour %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :subtotal %><br>
    <%= f.text_field :subtotal %>
  </div>
  <div class="field">
    <%= f.label :iva %><br>
    <%= f.text_field :iva %>
  </div>
  <div class="field">
    <%= f.label :total_effective %><br>
    <%= f.text_field :total_effective %>
  </div>
  <div class="field">
    <%= f.label :total_card %><br>
    <%= f.text_field :total_card %>
  </div>
  <div class="field">
    <%= f.label :total_checks %><br>
    <%= f.text_field :total_checks %>
  </div>
  <div class="field">
    <%= f.label :nota %><br>
    <%= f.text_area :nota %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Hour</th>
      <th>Client</th>
      <th>User</th>
      <th>Subtotal</th>
      <th>Iva</th>
      <th>Total effective</th>
      <th>Total card</th>
      <th>Total checks</th>
      <th>Nota</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.date %></td>
        <td><%= sale.hour %></td>
        <td><%= sale.client %></td>
        <td><%= sale.user %></td>
        <td><%= sale.subtotal %></td>
        <td><%= sale.iva %></td>
        <td><%= sale.total_effective %></td>
        <td><%= sale.total_card %></td>
        <td><%= sale.total_checks %></td>
        <td><%= sale.nota %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sale.date %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @sale.hour %>
</p>

<p>
  <strong>Client:</strong>
  <%= @sale.client %>
</p>

<p>
  <strong>User:</strong>
  <%= @sale.user %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @sale.subtotal %>
</p>

<p>
  <strong>Iva:</strong>
  <%= @sale.iva %>
</p>

<p>
  <strong>Total effective:</strong>
  <%= @sale.total_effective %>
</p>

<p>
  <strong>Total card:</strong>
  <%= @sale.total_card %>
</p>

<p>
  <strong>Total checks:</strong>
  <%= @sale.total_checks %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @sale.nota %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>